Repository prgrms-web-devcourse/FE-TEAM-Dong0-CoreJS-Study, pull requests merged in 2022-05, with the labels that each got.

#14 코어 자바스크립트 4장
  4장/4장_계진.md
Labels: 계진, 4장

#13 🎉 4장 완료
  4장/4장_혜경.md
Labels: 혜경, 4장

#18 🎉 5장 완료
  5장/5장_혜경.md
Labels: 혜경, 5장

#16 코어 자바스크립트 5장
  5장/5장_계진.md
  6장/6장_계진.md
Labels: 계진, 5장

#17 코어 자바스크립트 5장(클로저) 정리
  4장/4장_창헌.md
  5장/5장_창헌.md
  6장/6장_창헌.md
Labels: 창헌, 5장

#23 🎉 7장 완료
  7장/7장_혜경.md
Labels: 혜경
